In [1]:
import tensorflow as tf
import numpy as np

In [2]:
a = tf.placeholder(shape=(None, 50), dtype=tf.float32)

In [3]:
a.get_shape().as_list()

[None, 50]

In [23]:
import numpy as np


class DataGenerator(object):

    def __init__(self):
        """Construct a DataGenerator."""
        pass

    def next_batch(self, batch_size, N, train_mode=True):
        """Return the next `batch_size` examples from this data set."""

        # A sequence of random numbers from [0, 1]
        reader_input_batch = []

        # Sorted sequence that we feed to encoder
        # In inference we feed an unordered sequence again
        decoder_input_batch = []

        # Ordered sequence where one hot vector encodes position in the input array
        writer_outputs_batch = []
        for _ in range(N):
            reader_input_batch.append(np.zeros([batch_size, 1]))
        for _ in range(N + 1):
            decoder_input_batch.append(np.zeros([batch_size, 1]))
            writer_outputs_batch.append(np.zeros([batch_size, N + 1]))

        for b in range(batch_size):
            print shuffle
            print sequence
            print shuffled_sequence
            for i in range(N):
                reader_input_batch[i][b] = shuffled_sequence[i]
                if train_mode:
                    decoder_input_batch[i + 1][b] = sequence[i]
                else:
                    decoder_input_batch[i + 1][b] = shuffled_sequence[i]
                writer_outputs_batch[shuffle[i]][b, i + 1] = 1.0

            # Points to the stop symbol
            writer_outputs_batch[N][b, 0] = 1.0

        return reader_input_batch, decoder_input_batch, writer_outputs_batch

In [26]:
g = DataGenerator()

In [41]:
r, d, w = g.next_batch(1, 8, False)

[4 6 0 7 2 5 3 1]
[ 0.01920566  0.56949056  0.72847146  0.77985133  0.78301     0.79420168
  0.980741    0.98678914]
[ 0.78301     0.980741    0.01920566  0.98678914  0.72847146  0.79420168
  0.77985133  0.56949056]


In [42]:
w

[array([[ 0.,  0.,  0.,  1.,  0.,  0.,  0.,  0.,  0.]]),
 array([[ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  1.]]),
 array([[ 0.,  0.,  0.,  0.,  0.,  1.,  0.,  0.,  0.]]),
 array([[ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  1.,  0.]]),
 array([[ 0.,  1.,  0.,  0.,  0.,  0.,  0.,  0.,  0.]]),
 array([[ 0.,  0.,  0.,  0.,  0.,  0.,  1.,  0.,  0.]]),
 array([[ 0.,  0.,  1.,  0.,  0.,  0.,  0.,  0.,  0.]]),
 array([[ 0.,  0.,  0.,  0.,  1.,  0.,  0.,  0.,  0.]]),
 array([[ 1.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.]])]

In [43]:
r

[array([[ 0.78301]]),
 array([[ 0.980741]]),
 array([[ 0.01920566]]),
 array([[ 0.98678914]]),
 array([[ 0.72847146]]),
 array([[ 0.79420168]]),
 array([[ 0.77985133]]),
 array([[ 0.56949056]])]

In [44]:
d

[array([[ 0.]]),
 array([[ 0.78301]]),
 array([[ 0.980741]]),
 array([[ 0.01920566]]),
 array([[ 0.98678914]]),
 array([[ 0.72847146]]),
 array([[ 0.79420168]]),
 array([[ 0.77985133]]),
 array([[ 0.56949056]])]

In [45]:
not None

True

In [52]:
a = [tf.placeholder(shape=(1, 2), dtype=tf.float32, name="in")] * 3

In [53]:
tf.pack(a)

<tf.Tensor 'pack_2:0' shape=(3, 1, 2) dtype=float32>

In [108]:
a = np.arange(18).reshape(3, 3, 2)

In [109]:
a[:, [1, 2], :]

array([[[ 2,  3],
        [ 4,  5]],

       [[ 8,  9],
        [10, 11]],

       [[14, 15],
        [16, 17]]])

In [89]:
a[1, 0]

array([6, 7])

In [110]:
input = tf.constant(np.arange(10))

In [112]:
tf.pack(0, (input, np.arange(10)))

<tf.Tensor 'concat_2:0' shape=(20,) dtype=int64>